### ISSUE TITLE
Install Polymer 2.x in Ubuntu 16.04

### ISSUE THREAD

**Issue by souman-technicise** [shantu/LearningPolymer#6]
### What are you going to need to reinstall?

Before you begin, I suggest you get a list of your globally installed packages so you know what to reinstall later:

npm list -g --depth=0
Sample output:

/usr/lib
├── bower@1.3.12
├── grunt-cli@0.1.13
├── gulp@3.8.10
├── npm@1.4.28
└── yo@1.3.3
Tell npm to install packages to home

By default, npm installs packages under /usr/lib/node_modules or /usr/local/lib/node_modules depending on your OS / distribution.
If you’re curious, you can check like this:

npm config get prefix
Your install path is the output of the above command plus /node_modules.
So if the command outputs /usr/lib then your install path is /usr/lib/node_modules.

The first step is to get it to install to your home directory instead.

npm config set prefix ~/npm
Fix your paths

Next, you need to add the appropriate paths to your environment variables…

# open your .bashrc (Linux) or .bash_profile (Mac) file for editing:
nano ~/.bashrc # for Linux
# or...
nano ~/.bash_profile # for Mac if you haven't created a .bashrc file

# add these lines:
export PATH="$PATH:$HOME/npm/bin"
export NODE_PATH="$NODE_PATH:$HOME/npm/lib/node_modules"

# save the file and then enter this command to make the changes take effect:
. ~/.bashrc
# or...
. ~/.bash_profile
Take ownership

Now you need to take ownership of everything that has previously been installed in ~/.npm.
Anything that was previously installed using sudo npm install will be owned by root and will cause problems later.

# optionally check to see if anything is owned by root:
ls -la ~/.npm

# take ownership of everything in your ~/.npm directory (must be run with sudo):
sudo chown -R $USER:`id -g -n $USER` ~/.npm
Reinstall your global packages

Finally, reinstall all your global packages (the ones you checked for in the first step)… this time without sudo!

# no sudo necessary :)
npm install -g bower
npm install -g grunt-cli
npm install -g gulp
npm install -g yo
And that’s it – hopefully this helps someone.

**Comment by souman-technicise** [comment]
## Step1: nodejs & npm install
``` curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - ```
``` sudo apt-get install nodejs ```
or
``` sudo apt-get install -y nodejs ```

````
user@user-VirtualBox:~$ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
[sudo] password for user: 

## Installing the NodeSource Node.js v8.x repo...


## Populating apt-get cache...

+ apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:2 http://in.archive.ubuntu.com/ubuntu xenial InRelease                     
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:4 http://dl.google.com/linux/chrome/deb stable Release              
Hit:5 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease      
Hit:7 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done                     

## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/xenial/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js v8.x repo...

+ echo 'deb https://deb.nodesource.com/node_8.x xenial main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_8.x xenial main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:2 http://in.archive.ubuntu.com/ubuntu xenial InRelease                     
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                     
Get:4 https://deb.nodesource.com/node_8.x xenial InRelease [4,634 B]           
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Get:6 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]    
Get:8 https://deb.nodesource.com/node_8.x xenial/main Sources [763 B]          
Get:9 https://deb.nodesource.com/node_8.x xenial/main amd64 Packages [967 B]   
Get:10 https://deb.nodesource.com/node_8.x xenial/main i386 Packages [971 B]   
Get:11 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB] 
Fetched 314 kB in 3s (93.5 kB/s)                             
Reading package lists... Done

## Run `apt-get install nodejs` (as root) to install Node.js v8.x and npm

user@user-VirtualBox:~$ sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 467 not upgraded.
Need to get 12.5 MB of archives.
After this operation, 63.0 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_8.x xenial/main amd64 nodejs amd64 8.1.4-1nodesource1~xenial1 [12.5 MB]
Fetched 12.5 MB in 1min 35s (130 kB/s)                                         
Selecting previously unselected package nodejs.
(Reading database ... 177013 files and directories currently installed.)
Preparing to unpack .../nodejs_8.1.4-1nodesource1~xenial1_amd64.deb ...
Unpacking nodejs (8.1.4-1nodesource1~xenial1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up nodejs (8.1.4-1nodesource1~xenial1) ...
user@user-VirtualBox:~$ node -v
v8.1.4
user@user-VirtualBox:~$ npm -v
5.0.3

````

**Comment by souman-technicise** [comment]
### Resolved Error:
E: Could not get lock /var/cache/apt/archives/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/cache/apt/archives/

````
user@user-VirtualBox:~$ sudo mv /var/cache/apt/archives/lock /var/cache/apt/archives/lock_bak
user@user-VirtualBox:~$ sudo apt install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gyp javascript-common libjs-inherits libjs-jquery libjs-node-uuid
  libjs-underscore libuv1 libuv1-dev node-abbrev node-ansi
  node-ansi-color-table node-archy node-async node-block-stream
  node-combined-stream node-cookie-jar node-delayed-stream node-forever-agent
  node-form-data node-fstream node-fstream-ignore node-github-url-from-git
  node-glob node-graceful-fs node-gyp node-inherits node-ini
  node-json-stringify-safe node-lockfile node-lru-cache node-mime
  node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt
  node-normalize-package-data node-npmlog node-once node-osenv node-qs
  node-read node-read-package-json node-request node-retry node-rimraf
  node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent
  node-underscore node-which nodejs nodejs-dev python-pkg-resources
Suggested packages:
  apache2 | lighttpd | httpd node-hawk node-aws-sign node-oauth-sign
  node-http-signature debhelper python-setuptools
The following NEW packages will be installed:
  gyp javascript-common libjs-inherits libjs-jquery libjs-node-uuid
  libjs-underscore libuv1 libuv1-dev node-abbrev node-ansi
  node-ansi-color-table node-archy node-async node-block-stream
  node-combined-stream node-cookie-jar node-delayed-stream node-forever-agent
  node-form-data node-fstream node-fstream-ignore node-github-url-from-git
  node-glob node-graceful-fs node-gyp node-inherits node-ini
  node-json-stringify-safe node-lockfile node-lru-cache node-mime
  node-minimatch node-mkdirp node-mute-stream node-node-uuid node-nopt
  node-normalize-package-data node-npmlog node-once node-osenv node-qs
  node-read node-read-package-json node-request node-retry node-rimraf
  node-semver node-sha node-sigmund node-slide node-tar node-tunnel-agent
  node-underscore node-which nodejs nodejs-dev npm python-pkg-resources
0 upgraded, 58 newly installed, 0 to remove and 467 not upgraded.
Need to get 6,083 kB of archives.
After this operation, 30.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y

````

**Comment by souman-technicise** [comment]
## Step2: node.js
``` sudo apt install nodejs-legacy ```

**Comment by souman-technicise** [comment]
## Step2: Ensure that Git is installed
``` git --version ```

````
user@user-VirtualBox:~$ git --version
git version 2.7.4
````
## Step3: Install the latest version of Bower
``` sudo npm install -g bower ```

````
user@user-VirtualBox:~$ sudo npm install -g bower
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
+ bower@1.8.0
added 1 package in 20.586s
user@user-VirtualBox:~$ bower -v
1.8.0
````

**Comment by souman-technicise** [comment]
## Step4: Install Polymer CLI
``` sudo npm install -g polymer-cli ```

## Installation Error:
````
user@user-VirtualBox:~$ sudo npm install -g polymer-cli
[sudo] password for user: 
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm WARN deprecated @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/@types%2fbluebird failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443
/usr/bin/polymer -> /usr/lib/node_modules/polymer-cli/bin/polymer.js

> wd@1.3.0 install /usr/lib/node_modules/polymer-cli/node_modules/wd
> node scripts/build-browser-scripts

/usr/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/polymer-cli/node_modules/wd/build'
    at Object.fs.mkdirSync (fs.js:890:18)
    at sync (/usr/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:71:13)
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/wd/scripts/build-browser-scripts.js:6:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wd@1.3.0 install: `node scripts/build-browser-scripts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wd@1.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-07-12T10_43_28_786Z-debug.log
````

**Comment by souman-technicise** [comment]
```
 111  npm list -g --depth=0
  112  npm update -g
  113  npm i -g npm
  114  npm i -g npm@5.3.0
  115  sudo npm i -g npm
  116  npm update -g
  117  npm config get prefix
  118  ls /usr
  119  npm config set prefix ~/npm
  120  vim ~/.bashrc 
  121  gedit ~/.bashrc 
  122  tail ~/.bashrc 
  123  exit
  124  ls -la ~/.npm
  125  sudo chown -R $USER:`id -g -n $USER` ~/.npm
  126  npm install -g bower
  127  npm config get prefix
  128  npm list -g --depth=0
  129  pwd
  130  ls
  131  cd code/
  132  ls
  133  npm install -g polymer-cli
  134  npm update -g
  135  ls
  136  mkdir polymer-sample
  137  cd polymer-sample/
  138  polymer init
  139  ls
  140  polymer serve
```

**Comment by souman-technicise** [comment]
Polymer 2.0 can't install in virtual machine...

**Comment by Shyam-technicise** [comment]
**gedit ~/.bashrc**  is not working
![screenshot from 2018-01-02 17-27-17](https://user-images.githubusercontent.com/13086777/34488699-7b2da452-efff-11e7-83c4-3db1d88f1c05.png)

```
** (gedit:10922): WARNING **: Set document metadata failed: Setting attribute metadata::gedit-spell-enabled not supported

** (gedit:10922): WARNING **: Set document metadata failed: Setting attribute metadata::gedit-encoding not supported


```

**Comment by Shyam-technicise** [comment]
**Got success on this way**...............

```
npm list -g --depth=0
npm config get prefix
npm config set prefix ~/npm
```
Added the appropriate paths to environment variables…
```
vim ~/.bashrc 
```
Addad following at the end : 
```
export PATH="$PATH:$HOME/npm/bin"
export NODE_PATH="$NODE_PATH:$HOME/npm/lib/node_modules"
```
Saved the file and then entered this command to make the changes take effect:
` . ~/.bashrc`
```
  ls -la ~/.npm
  sudo chown -R $USER:id -g -n $USER ~/.npm
  sudo chown -R $USER:id -n $USER ~/.npm
```
